/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package small_management_program;

import small_management_program.view.View;

public class Launcher {
    public static void main(String[] args) {
        View.launch(View.class, args);
    }
}
